info:
  component: 'Locationservice'

spring:
    application:
        name: locations
    zipkin:
        baseUrl: http://10.1.101.6:9411
    sleuth:
        enabled: true
        sampler:
            percentage: 1.0

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

---
# For deployment without Docker containers
spring:
  profiles: default

server:
    port: 8081


---
# For deployment in Docker containers
spring:
  profiles: docker

server:
    port: 80